### ISSUE TITLE
Criar script para importar dados dos servidores

### ISSUE THREAD

**Issue by atilacamurca** [ifce-gp-20151/saa#13]

**Comment by atilacamurca** [comment]
Backup de desenvolvimento do SiRem, contendo as tabelas a serem importadas.

https://www.dropbox.com/s/nhpl1p4wgv2v561/sirem-dev-11mar2015.backup?dl=0

Daí podemos importas os `public.cargos`, `public.pessoa` e `public.servidor`.

**Comment by aldisio** [comment]
Senhores, boa tarde.

Informo que fiz o script de migração das tabelas servidores,cargo e pessoa da base do SIREM para o SAA.

Passo a Passo da migração:
1- Faça a importação do arquivo de backup(sirem.backup) da base de dados do SIREM (Manual de como fazer restore: http://get.enterprisedb.com/docs/Tutorial_All_PP_pgAdmin_Backup_Restore.pdf);
1.1 -  As tabelas importadas do SIREM terão o schema public;

2- Após o restore, execute o arquivo Migrate_SIREN2SAA.sql;
3 - Remova as tabelas do schema public importadas no restore do SIREM.

**Comment by atilacamurca** [comment]
Boa, vou pegar os dados reais e fazer o restore.

Tu lembrou de levar em conta que já existem dados na tabela pessoa? (ou seja os id's não iniciam do número 1)
