### ISSUE TITLE
Criar script para importar dados dos alunos

### ISSUE THREAD

**Issue by atilacamurca** [ifce-gp-20151/saa#7]
O cadastro do alunos e servidores (TAE e Professores) pode ser importado de bases de dados já existentes, como Qacadêmico e SiRem.

Criar script que faça a importação de acordo com as tabelas do nosso banco.

**Comment by atilacamurca** [comment]
Conversando com o Prof. Daniel, ele falou que o Qacadêmico disponibiliza um dump dos dados dos alunos em formato CSV.

Poderíamos usar o http://pgloader.io/howto/csv.html para fazer a importação.

**Comment by aldisio** [comment]
Criado o script de migração e população das tabelas a partir do arquivo csv do QAcademicos.
