### ISSUE TITLE
Importar profissões

### ISSUE THREAD

**Issue by atilacamurca** [ifce-gp-20151/saa#9]
Criar script para importar as profissões da **Classificação Brasileira de Ocupações**.

 LInk para download: http://www.mtecbo.gov.br/cbosite/pages/downloads.jsf

**Comment by lucasssousa10** [comment]
Já realizei o commit do script para inserção das profissões, bem como os de alteração do DDL do banco de dados pra que sejam recebidos os dados corretamente. 

A chave primária da tabela de Profissões teve seu tipo de dado alterado para varchar para que o código CBO fosse utilizado como chave primária da tabela. Por consequência disso, as sequences foram retiradas também e todas as referências de chaves estrangeiras tiveram seus tipos também alterados.
